import { describe, it, expect } from "vitest";
import { generateDts } from "../application/generateDts";

describe("generateDts", () => {
  it("includes the auto-generated header comment", () => {
    const result = generateDts([]);
    expect(result).toContain("Auto-generated by sj-web-crate");
  });

  it("generates a declare module block for a single collection", () => {
    const result = generateDts([{ name: "artist", dir: "src/artists" }]);
    expect(result).toContain("declare module 'virtual:sj-web-crate/artist'");
  });

  it("generates declare module blocks for multiple collections", () => {
    const result = generateDts([
      { name: "artist", dir: "src/artists" },
      { name: "project", dir: "src/projects" },
    ]);
    expect(result).toContain("declare module 'virtual:sj-web-crate/artist'");
    expect(result).toContain("declare module 'virtual:sj-web-crate/project'");
  });

  it("each module exports entries and slugs", () => {
    const result = generateDts([{ name: "artist", dir: "src/artists" }]);
    expect(result).toContain("export const entries: Entry[]");
    expect(result).toContain("export const slugs: string[]");
  });

  it("Entry interface has slug, data, and body fields", () => {
    const result = generateDts([{ name: "artist", dir: "src/artists" }]);
    expect(result).toContain("slug: string");
    expect(result).toContain("data: Record<string, unknown>");
    expect(result).toContain("body: string");
  });

  it("returns empty module list for empty collections array", () => {
    const result = generateDts([]);
    expect(result).not.toContain("declare module");
  });

  it("uses the collection name in the module path, not the dir", () => {
    const result = generateDts([{ name: "artist", dir: "some/other/path" }]);
    expect(result).toContain("virtual:sj-web-crate/artist");
    expect(result).not.toContain("some/other/path");
  });
});
