import type { CrateConfig } from "../domain/types.ts";

export function generateDts(crates: CrateConfig[]): string {
  const modules = crates
    .map((c) => {
      return `  declare module 'virtual:sj-web-crate/${c.name}' {
    export interface Entry {
      slug: string;
      data: Record<string, unknown>;
      body: string;
    }
    export const entries: Entry[];
    export const slugs: string[];
  }`;
    })
    .join("\n\n");

  return `// Auto-generated by sj-web-crate — do not edit manually\n\n${modules}\n`;
}
