// Auto-generated by sj-web-crate — do not edit manually

  declare module 'virtual:sj-web-crate/artist' {
    export interface Entry {
      slug: string;
      data: Record<string, unknown>;
      body: string;
    }
    export const entries: Entry[];
    export const slugs: string[];
  }
